# Generated by Django 3.0.8 on 2020-07-07 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_auto_20200707_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='saved',
        ),
    ]
