# Generated by Django 3.0.8 on 2020-07-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0008_auto_20200707_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
