# Generated by Django 3.0.8 on 2020-07-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0009_post_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='saved',
        ),
    ]
