# Generated by Django 3.0.8 on 2020-07-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200708_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to='accounts.Profile'),
        ),
    ]
